name: Generate README

on:
  pull_request:
    branches: [ main ]
    paths:
      - '_data/resources.yml'
      - 'scripts/generate_readme.rb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false

      - name: Generate README
        run: ruby scripts/generate_readme.rb

      - name: Fail if README not up to date
        run: |
          if ! git diff --quiet README.md; then
            echo 'README.md is out of date. Please run scripts/generate_readme.rb and commit the result.' >&2
            git --no-pager diff README.md
            exit 1
          fi
