name: Link Check

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
  pull_request:
    paths:
      - 'README.md'
      - '_data/resources.yml'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-mail
            --accept 200,301,302,307,308
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate failures
        if: failure()
        run: echo 'Some links appear broken. Please verify and update resources.'
