name: Validate Data

on:
  pull_request:
    paths:
      - '_data/**'
      - 'scripts/validate.rb'
  push:
    branches: [ main ]
    paths:
      - '_data/**'
      - 'scripts/validate.rb'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false
      - name: Run validator
        run: ruby scripts/validate.rb
